# Generated by Django 3.0.6 on 2020-08-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapp', '0002_auto_20200817_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprador',
            options={'verbose_name_plural': 'Compradores'},
        ),
        migrations.AddField(
            model_name='comprador',
            name='celular',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comprador',
            name='detalle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cant',
            field=models.IntegerField(null=True),
        ),
    ]
