# Generated by Django 3.0.6 on 2020-09-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapp', '0004_pedido_pu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name_plural': 'Pedidos'},
        ),
    ]
