# Generated by Django 3.0.6 on 2020-09-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapp', '0005_auto_20200912_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
