# Generated by Django 3.0.6 on 2020-09-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapp', '0006_pedido_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='selected',
            new_name='a_entregar',
        ),
    ]
