# Generated by Django 3.0.6 on 2020-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapp', '0007_auto_20200914_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pu',
            field=models.FloatField(null=True),
        ),
    ]
